"""
APT Simulator — Stage 1.5: Physical Tampering
=============================================
Simulates physical access to the smart meter via optical port.
Attacker attempts to inject a malicious/replayed recharge token.
"""

from __future__ import annotations

import asyncio
import logging
from datetime import datetime, timezone

from shared.event_bus import EventBus
from shared.models import AttackStage
from attacker.event_log import EventLog

logger = logging.getLogger(__name__)

STAGE = AttackStage.PHYSICAL_TAMPER
TECHNIQUE_ID = "T0834"
TACTIC = "Initial Access"

async def execute(
    event_log: EventLog,
    stage_config: dict = None,
    **kwargs
) -> dict:
    """Execute physical tampering stage."""
    stage_config = stage_config or {}
    target_meter = stage_config.get("target_meter", "SM-A-0001")
    token = stage_config.get("token", "2938 1234 9876 5432 1098")
    
    event_bus = EventBus.get_instance()
    
    logger.info(f"[TAMPER] Connecting to optical port of {target_meter}")
    await event_log.log_event(
        stage=STAGE,
        technique_id=TECHNIQUE_ID,
        tactic=TACTIC,
        target="Optical Port",
        action=f"Connecting to optical port of {target_meter}",
        details={"meter_id": target_meter}
    )
    
    await asyncio.sleep(2)
    
    logger.info(f"[TAMPER] Injecting malicious token: {token}")
    # We publish it as telemetry or event so the dashboard can potentially see it, but we mainly care about detector picking it up.
    await event_bus.publish(
        f"meters/{target_meter}/events",
        {
            "event": "token_recharge_attempt",
            "token": token,
            "meter_id": target_meter,
            "timestamp": datetime.now(timezone.utc).isoformat()
        }
    )
    
    await event_log.log_event(
        stage=STAGE,
        technique_id=TECHNIQUE_ID,
        tactic=TACTIC,
        target="Optical Port",
        action=f"Injected malicious recharge token",
        details={"meter_id": target_meter, "token": token}
    )
    
    await asyncio.sleep(3)
    
    logger.info(f"[TAMPER] Token REJECTED by meter {target_meter}")
    # Simulating the meter responding with a reject
    await event_bus.publish(
        f"meters/{target_meter}/events",
        {
            "event": "token_rejected",
            "reason": "invalid_signature",
            "meter_id": target_meter,
            "timestamp": datetime.now(timezone.utc).isoformat()
        }
    )
    
    await event_log.log_event(
        stage=STAGE,
        technique_id=TECHNIQUE_ID,
        tactic=TACTIC,
        target="Optical Port",
        action=f"Token REJECTED / REFUND event generated by meter",
        details={"meter_id": target_meter, "status": "failed", "reason": "invalid_signature"}
    )
    
    return {
        "success": False, 
        "target": target_meter, 
        "status": "Token rejected by meter", 
        "blocked_by_detection": False
    }
